### ISSUE TITLE
इष्ठन् 

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-lexicon/csl-ldev#5]
https://github.com/sanskrit-lexicon/csl-ldev/pull/4/files closed by mistake I think
 can you fix?

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-ldev/blob/main/v02/vcp/34929.txt has it corrected.

**Comment by drdhaval2785** [comment]
The reason why it was not merged was that the base text file at CDSL had undegone major changes in the interim.
Therefore conveying this change from csl-ldev -> csl-devanagari -> csl-orig data would have led to conflicts.
Therefore I changed the data directly in csl-orig then csl-devanagari -> csl-ldev.
